### ISSUE TITLE
Suggested improvement app

### ISSUE THREAD

**Issue by TammievanBiemen** [footballdaniel/algorithmicvalidation#1]
**Current version:** application saves the selected option when going a frame forward AND going a frame backwards. 

**Problem:** sometimes you want to adjust or check a AOI of what is happening a few frames later. But when going backwards, you actually can't see what you selected earlier because it is overwritten by the last selected option. 

**Suggestion new version:** save selection option when going a frame forward BUT keep previous input when going a frame backwards

**Comment by TammievanBiemen** [comment]
**Current version:** Once you press "Download results" everything is saved up untill the frame you have open. So the last frame is never saved. 

**Suggestion new version:** Include the current frame which is open on your screen in the "Download results"

**Comment by footballdaniel** [comment]
Good point, I changed it. Now the choice is only saved when clicking on `Next Image`
